---
version: 0.1.6
slug: kamstrup
name: Kamstrup 402 & 403 Logger
description: Kamstrup Warmtemeter data logger
url: https://github.com/jrkalf/kamstrup-40x-mqtt-hassio
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
auth_api: true
services:
  - mqtt:need
options:
  mqtt_host: "10.10.10.10"
  mqtt_port: "1883"
  mqtt_username: "homeassistant"
  mqtt_password: "ultrasecretstuffhappenshere"
  mqtt_authentication: "true"
  serial_device: "/dev/ttyUSB0"
  poll_interval: "28"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  mqtt_authentication: bool
  serial_device: device(subsystem=tty)
  poll_interval: int
init: false
